import "../styles/global.css";

import { Metadata } from "next";
import Navigate from "../components/navigate";

export const metadata: Metadata = {
  title: {
    template: "%s | NextJS",
    default: "Loading ...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigate />
        {children}
      </body>
    </html>
  );
}
